# Generated by Django 5.0.3 on 2024-03-25 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('major', models.CharField(max_length=127)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
