# Generated by Django 5.0.3 on 2024-03-26 05:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='semesters',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
        migrations.AddField(
            model_name='student',
            name='userKey',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
